lib: [
  "_build/install/default/lib/summer/META" {"META"}
  "_build/install/default/lib/summer/opam" {"opam"}
  "_build/install/default/lib/summer/summer.cmi" {"summer.cmi"}
  "_build/install/default/lib/summer/summer.cmx" {"summer.cmx"}
  "_build/install/default/lib/summer/summer.cmt" {"summer.cmt"}
  "_build/install/default/lib/summer/summer.ml" {"summer.ml"}
  "_build/install/default/lib/summer/summer.cma" {"summer.cma"}
  "_build/install/default/lib/summer/summer.cmxa" {"summer.cmxa"}
  "_build/install/default/lib/summer/summer.a" {"summer.a"}
  "_build/install/default/lib/summer/summer.cmxs" {"summer.cmxs"}
  "_build/install/default/lib/summer/summer.dune" {"summer.dune"}
]
bin: [
  "_build/install/default/bin/tests" {"tests"}
  "_build/install/default/bin/summer" {"summer"}
]
doc: [
  "_build/install/default/doc/summer/README.org"
]
